#! /bin/bash

# Test includes
source "$SH_PATH_UTILS/testing_framework.sh"

# Sources
source "$SH_PATH_LIB/get_variables.sh"

test_getVariables(){
  test_and_assert --fnc "get_variables" -An "$@"
}

G_STEP_CHECKARG="checkArg"
G_STEP_CHECKBUILD="checkBuild"
G_STEP_CHECKREPOPATCH="checkRepo"
G_STEP_CHECKUSER="checkUser"
G_STEP_REPOCREATION="repoCreation"
G_STEP_S2KRUNNING="s2krunning"
G_STEP_SETGLOBALVAR_REPODIR="setGloVarRepoDirs"
G_STEP_SETPATCHID="setPatchId"

G_MODE_NAME_CLEAN="CLEAN"
G_MODE_NAME_CREATE="CREATE"
G_MODE_NAME_LIST="LIST"
G_MODE_NAME_PATCH="PATCH"
G_MODE_NAME_RESTORE="RESTORE"
G_MODE_NAME_RESTORE_ALL="RESTORE_ALL"
G_MODE_DEFAULT="$G_MODE_PATCH"
G_MODE="$G_MODE_DEFAULT"
G_MODE_CONFIG_CLEAN=""
G_MODE_CONFIG_CREATE=""
G_MODE_CONFIG_LIST=""
G_MODE_CONFIG_PATCH=""
G_MODE_CONFIG_RESTORE=""
G_MODE_CONFIG_RESTORE_ALL=""
G_MODE_CONFIG_CURRENT=""

test_getVariables $'' ""
test_getVariables $'G_MODE_NAME_CLEAN\nG_MODE_NAME_CREATE\nG_MODE_NAME_LIST\nG_MODE_NAME_PATCH\nG_MODE_NAME_RESTORE\nG_MODE_NAME_RESTORE_ALL' "G_MODE_NAME_.+"
test_getVariables $'G_STEP_CHECKARG\nG_STEP_CHECKBUILD\nG_STEP_CHECKREPOPATCH\nG_STEP_CHECKUSER\nG_STEP_REPOCREATION\nG_STEP_S2KRUNNING\nG_STEP_SETGLOBALVAR_REPODIR\nG_STEP_SETPATCHID' "G_STEP_.+"
test_getVariables '' 'testouille.*'
test_getVariables $'G_MODE_CONFIG_CREATE' 'G_MODE_CONFIG_CREATE'
